### ISSUE TITLE
Installation Appears Correct, but Missing ffilupa.lua, _ffilupa.so

### ISSUE THREAD

**Issue by phartleyp** [TitanSnow/ffilupa#5]
Using Windows Subsystem for Linux (Ubuntu 18.04).

Install ffilupa according to the instructions...
```
sudo apt-get install liblua5.2-dev
sudo apt-get install python3-dev
pip3 install ffilupa
```

Installation appears to have been successful--no errors reported...
```
Collecting ffilupa
Collecting cffi~=1.10 (from ffilupa)
  Using cached https://files.pythonhosted.org/packages/5f/bf/6aa1925384c23ffeb579e97a5569eb9abce41b6310b329352b8252cee1c3/cffi-1.12.3-cp36-cp36m-manylinux1_x86_64.whl
Collecting semantic-version~=2.2 (from ffilupa)
  Using cached https://files.pythonhosted.org/packages/28/be/3a7241d731ba89063780279a5433f5971c1cf41735b64a9f874b7c3ff995/semantic_version-2.6.0-py3-none-any.whl
Collecting pycparser (from cffi~=1.10->ffilupa)
Installing collected packages: pycparser, cffi, semantic-version, ffilupa
Successfully installed cffi-1.12.3 ffilupa-3.0.1 pycparser-2.19 semantic-version-2.6.0
```

After installation, I can successfully execute lua scripts from within python.  However if I want to go the other way around, the `require "ffilupa"` in python fails because the necessary .lua or .so files are completely absent from filesystem.  This isn't a LUA_PATH problem... there is no file matching ffilupa.* or _ffilupa.* anywhere.  Seems like something didn't get built.

I retried by doing pip uninstall and then pip install from Git HEAD, but no change.

**Comment by phartleyp** [comment]
Nevermind...  I was mislead by the instructions "For Python Users" and "For Lua Users" into thinking that these two sections of the instructions were mutually exclusive.  It turns out that both Python and Lua users need to execute both sets of instructions.

**Comment by TitanSnow** [comment]
Well, `import ffilupa` in Python needs you to install ffilupa according to the instructions listed in "For Python Users" and `require "ffilupa"` in Lua needs you to install ffilupa according to the instructions listed in "For Lua Users". If you write both Lua and Python, you can install twice, one for Lua and one for Python, but I think it's a corner case.

> However if I want to go the other way around, the `require "ffilupa"` in python fails because the necessary .lua or .so files are completely absent from filesystem.

What is "`require "ffilupa"` in python"? Do you mean open a LuaRuntime in Python, and then execute `require "ffilupa"` in it? If so, well, it's a wrong usage. You can use the global variable `python` already registered, which is the same as `lupa`. You can use it like this:

```python
import ffilupa
with ffilupa.LuaRuntime() as lua:
    lua.execute('setattr = python.setattr')
    lua.execute('runtime = python.runtime')
    lua.execute('ffilupa = python.ffilupa')

**Comment by phartleyp** [comment]
> Do you mean open a LuaRuntime in Python, and then execute require "ffilupa" in it?

Yes, exactly.

I had thought that i needed `import ffilupa` in Python to evaluate Lua from Python, and a corresponding `require "ffilupa"` in Lua to evaluate Python from Lua.  So I was I was wrongly trying to do something like this in Python:
```python
import ffilupa

lua = ffilupa.LuaRuntime()
lua.execute('ffilupa = require "ffilupa"')
lua.execute('bar = ffilupa.import_module("foo").bar')
lua.execute('bar("baz")')
```

This stems from limited documentation and a misunderstanding on my part about how ffilupa works, without benefit of having used lupa in the past.  I did not know that the global variable python was registered in the Lua environment--this variable is documented in only in the lupa documentation.

**Comment by TitanSnow** [comment]
I'm to blame for the poor documentation. In fact, I have little free time on my projects on GitHub and the development of ffilupa seems stagnant. But I'm sure that if I were to have enough spare time, I would settle down to it, re-writing the documentation and the unittest.
